all: filemain.cpp fullmain.cpp fulltransform.hpp halfmain.cpp halftransform.hpp hmatrix.hpp imatrix.hpp Makefile
	#g++ -g halfmain.cpp -o hadamard.`uname`
	#g++ -g fullmain.cpp -o hadamard.`uname`
	g++ -g filemain.cpp -o hadamard.`uname`

clean:
	rm -f hadamard.`uname` dump
