all:	testarithmetic.cpp testbigint.cpp arithmetic.hpp bigint.hpp Makefile
	#g++ -o3 -g -Wall testbigint.cpp -o testbigint.`uname`
	g++ -o3 -g -Wall testarithmetic.cpp -o testarithmetic.`uname`
	#g++ -o3 -g -Wall testsignedarithmetic.cpp -o testsignedarithmetic.`uname`

clean:
	rm -f *.`uname` core.* dump *.out
